<?php
/**
 * The WPCBL_Check_Broken_Links_Admin_Export class.
 *
 * @package WPCBL_Check_Broken_Links/Admin
 * @author  Norse Digital Group LLC
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! class_exists( 'WPCBL_Check_Broken_Links_Admin_Export' ) ) :

	/**
	 * Admin report.
	 *
	 * Exports the scan results. CSV is free; XLSX, TXT, and Markdown are Pro.
	 *
	 * @since 1.0.0
	 */
	class WPCBL_Check_Broken_Links_Admin_Export {
		/**
		 * The constructor.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function __construct() {
			// Actions.
			add_action( 'admin_init', array( $this, 'export_report' ) );
		}

		/**
		 * Convert a CSV row array into a correctly escaped CSV line.
		 *
		 * @since 2.0.1
		 *
		 * @param array $row CSV row values.
		 *
		 * @return string
		 */
		private function csv_row( $row ) {
			$handle = fopen( 'php://temp', 'r+' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen

			if ( false === $handle ) {
				return '';
			}

			fputcsv( $handle, $row, ",", '"', "\\" ); // phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.file_ops_fputcsv
			rewind( $handle );
			$line = stream_get_contents( $handle );
			fclose( $handle ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose

			return false === $line ? '' : $line;
		}

		/**
		 * Get a readable source name for the export.
		 *
		 * @since 2.0.1
		 *
		 * @param array $link Broken link row.
		 *
		 * @return string
		 */
		private function get_source_name( $link ) {
			if ( isset( $link['source_label'] ) && '' !== $link['source_label'] ) {
				return wp_strip_all_tags( $link['source_label'] );
			}

			$title = wpcbl_get_post_or_comment_title( $link );

			return ! empty( $title ) ? wp_strip_all_tags( $title ) : '';
		}

		/**
		 * Collect the report rows: broken links first, then warnings.
		 *
		 * @since 3.0.0
		 *
		 * @return array Array of associative rows.
		 */
		private function get_report_rows() {
			$links = get_option( 'wpcbl_check_for_broken_links_links', array() );
			$rows  = array();

			foreach ( array( 'broken', 'warning' ) as $bucket ) {
				if ( empty( $links[ $bucket ] ) || ! is_array( $links[ $bucket ] ) ) {
					continue;
				}
				foreach ( $links[ $bucket ] as $link ) {
					$rows[] = array(
						'url'       => esc_url_raw( $link['link'] ),
						'status'    => sanitize_text_field( $link['type'] ),
						'code'      => sanitize_text_field( $link['code'] ),
						'message'   => sanitize_text_field( $link['text'] ),
						'source_id' => isset( $link['ID'] ) ? absint( $link['ID'] ) : '',
						'source'    => $this->get_source_name( $link ),
						'post_type' => wp_strip_all_tags( wpcbl_get_post_or_comment_type( $link ) ),
						'date'      => sanitize_text_field( $link['detected_at'] ),
					);
				}
			}

			return $rows;
		}

		/**
		 * The column headers shared by every format.
		 *
		 * @since 3.0.0
		 *
		 * @return array
		 */
		private function get_report_headers() {
			return array( 'Link', 'Status', 'Code', 'Message', 'SourceId', 'SourceName', 'SourcePostType', 'Date' );
		}

		/**
		 * Build the CSV report body.
		 *
		 * @since 3.0.0
		 *
		 * @param array $rows Report rows.
		 *
		 * @return string
		 */
		private function build_csv( $rows ) {
			$content = $this->csv_row( $this->get_report_headers() );

			foreach ( $rows as $row ) {
				$content .= $this->csv_row( array_values( $row ) );
			}

			return $content;
		}

		/**
		 * Build the plain text report body (Pro).
		 *
		 * @since 3.0.0
		 *
		 * @param array $rows Report rows.
		 *
		 * @return string
		 */
		private function build_txt( $rows ) {
			$content  = sprintf( 'Broken links report for %s', home_url() ) . "\n";
			$content .= sprintf( 'Generated %s. %d rows.', gmdate( 'Y-m-d H:i' ), count( $rows ) ) . "\n";
			$content .= str_repeat( '=', 60 ) . "\n\n";

			foreach ( $rows as $row ) {
				$content .= 'URL:      ' . $row['url'] . "\n";
				$content .= 'Status:   ' . $row['status'] . ' (' . $row['code'] . ' ' . $row['message'] . ')' . "\n";
				$content .= 'Found in: ' . $row['source'] . ' [' . $row['post_type'] . ']' . "\n";
				$content .= 'Detected: ' . $row['date'] . "\n";
				$content .= str_repeat( '-', 60 ) . "\n";
			}

			return $content;
		}

		/**
		 * Build the Markdown report body, prompt-ready for AI assistants (Pro).
		 *
		 * @since 3.0.0
		 *
		 * @param array $rows Report rows.
		 *
		 * @return string
		 */
		private function build_md( $rows ) {
			$md_escape = function ( $value ) {
				return str_replace( array( '|', "\n" ), array( '\|', ' ' ), (string) $value );
			};

			$content  = '# Broken links report for ' . home_url() . "\n\n";
			$content .= sprintf( 'Generated by Check for Broken Links on %s. %d rows below.', gmdate( 'Y-m-d H:i' ), count( $rows ) ) . "\n\n";
			$content .= "You are my WordPress assistant. For each row in the table below, suggest the most likely working replacement URL, or recommend removing the link when no replacement exists. Only suggest URLs you are confident exist, and say so when you are unsure. Answer with a table: Original URL | Suggested action | Replacement URL | Reason.\n\n";
			$content .= "| URL | Status | Code | Message | Found in | Content type | Detected |\n";
			$content .= "|---|---|---|---|---|---|---|\n";

			foreach ( $rows as $row ) {
				$content .= '| ' . implode(
					' | ',
					array(
						$md_escape( $row['url'] ),
						$md_escape( $row['status'] ),
						$md_escape( $row['code'] ),
						$md_escape( $row['message'] ),
						$md_escape( $row['source'] ),
						$md_escape( $row['post_type'] ),
						$md_escape( $row['date'] ),
					)
				) . " |\n";
			}

			return $content;
		}

		/**
		 * Build a minimal single-sheet XLSX file using ZipArchive, no external
		 * libraries. Strings are stored inline to keep the file simple (Pro).
		 *
		 * @since 3.0.0
		 *
		 * @param array $rows Report rows.
		 *
		 * @return string|false Binary XLSX content, or false on failure.
		 */
		private function build_xlsx( $rows ) {
			if ( ! class_exists( 'ZipArchive' ) ) {
				return false;
			}

			$xml_cell = function ( $value ) {
				return '<c t="inlineStr"><is><t>' . htmlspecialchars( (string) $value, ENT_XML1 | ENT_QUOTES, 'UTF-8' ) . '</t></is></c>';
			};

			$sheet_rows = '<row>';
			foreach ( $this->get_report_headers() as $header ) {
				$sheet_rows .= $xml_cell( $header );
			}
			$sheet_rows .= '</row>';

			foreach ( $rows as $row ) {
				$sheet_rows .= '<row>';
				foreach ( array_values( $row ) as $value ) {
					$sheet_rows .= $xml_cell( $value );
				}
				$sheet_rows .= '</row>';
			}

			$files = array(
				'[Content_Types].xml'        => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
				'_rels/.rels'                => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
				'xl/workbook.xml'            => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Broken links" sheetId="1" r:id="rId1"/></sheets></workbook>',
				'xl/_rels/workbook.xml.rels' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
				'xl/worksheets/sheet1.xml'   => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>' . $sheet_rows . '</sheetData></worksheet>',
			);

			$tmp = wp_tempnam( 'wpcbl-report' );
			$zip = new ZipArchive();
			if ( true !== $zip->open( $tmp, ZipArchive::OVERWRITE ) ) {
				return false;
			}
			foreach ( $files as $name => $content ) {
				$zip->addFromString( $name, $content );
			}
			$zip->close();

			$binary = file_get_contents( $tmp ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local temp file created by wp_tempnam.
			wp_delete_file( $tmp );

			return $binary;
		}

		/**
		 * Handle the export form: build the requested format and stream it.
		 * CSV is free; every other format needs Pro.
		 *
		 * @since 1.0.0
		 *
		 * @return void
		 */
		public function export_report() {
			// Check if we are on the correct page.
			if ( ! isset( $_GET['page'] ) || 'wpcbl-check-for-broken-links' !== sanitize_text_field( wp_unslash( $_GET['page'] ) ) ) {
				return;
			}

			// Check if our form has been submitted (the legacy action name still works).
			if ( ! isset( $_POST['action'] ) || ! in_array( sanitize_text_field( wp_unslash( $_POST['action'] ) ), array( 'wpcbl_export_report', 'wpcbl_export_csv' ), true ) ) {
				return;
			}

			// Verify the nonce.
			if ( ! isset( $_POST['nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['nonce'] ) ), 'wpcbl_export_csv_nonce' ) ) {
				wp_die( esc_html__( 'Cheatin&#8217; huh?', 'check-for-broken-links' ) );
			}

			// Check if the current user can manage options.
			if ( ! current_user_can( 'manage_options' ) ) {
				wp_die( esc_html__( 'You do not have sufficient permissions to access this page.', 'check-for-broken-links' ) );
			}

			$format = isset( $_POST['format'] ) ? sanitize_key( wp_unslash( $_POST['format'] ) ) : 'csv';
			if ( ! in_array( $format, array( 'csv', 'txt', 'md', 'xlsx' ), true ) ) {
				$format = 'csv';
			}

			// CSV is the free format; everything else is Pro.
			if ( 'csv' !== $format && ! wpcbl_has_pro() ) {
				wp_die( esc_html__( 'XLSX, TXT, Markdown and PDF reports are Pro features.', 'check-for-broken-links' ) );
			}

			$rows           = $this->get_report_rows();
			$generated_date = gmdate( 'd-m-Y His' );
			$filename       = "broken_links_report_{$generated_date}.{$format}";

			switch ( $format ) {
				case 'txt':
					$output       = $this->build_txt( $rows );
					$content_type = 'text/plain; charset=utf-8';
					break;

				case 'md':
					$output       = $this->build_md( $rows );
					$content_type = 'text/markdown; charset=utf-8';
					break;

				case 'xlsx':
					$output       = $this->build_xlsx( $rows );
					$content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
					if ( false === $output ) {
						wp_die( esc_html__( 'XLSX export needs the PHP zip extension, which is not available on this server. Use CSV instead.', 'check-for-broken-links' ) );
					}
					break;

				default:
					$output       = $this->build_csv( $rows );
					$content_type = 'text/csv; charset=utf-8';
					break;
			}

			// Send headers for download.
			header( 'Content-Type: ' . $content_type );
			header( 'Content-Disposition: attachment; filename="' . esc_attr( $filename ) . '"' );
			header( 'Pragma: no-cache' );
			header( 'Expires: 0' );

			echo $output; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- File download body, not HTML.

			exit;
		}
	}

	return new WPCBL_Check_Broken_Links_Admin_Export();

endif;
